import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="bg-slate-900 text-white p-4 text-center">
            <Navigation />
          </header>
          {children}
          <footer className="fixed bottom-0 left-0 right-0 z-10 flex items-center justify-center w-full h-[var(--geist-footer-height)] bg-background border-t border-solid border-black/[.08] dark:border-white/[.145]">
            <div className="flex items-center gap-2">
              <span className="text-sm text-foreground">
                © 2025 Next.js App. All rights reserved.
              </span>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
